image:
  name: node:13.1.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules

before_script:
  - yarn

stages:
  - test
  - lint

test:
  stage: test
  only:
    refs:
      - merge_requests
  script:
    - yarn run test:ci
  artifacts:
    expose_as: 'Test Coverage'
    paths:
      - coverage/lcov-report/
    reports:
      junit: ./junit.xml
  coverage: /All files +\| +\d+\.?\d*/

lint:
  stage: lint
  only:
    refs:
      - merge_requests
  script:
    - yarn run lint
